version: 2.1
orbs:
  # python: circleci/python@1.3.2
  heroku: circleci/heroku@1.0.1

executors:
  python:
    docker:
      - image: circleci/python:3.8-buster
        environment:
          DB_DATABASE: kbpartpicker
          DB_HOST: "127.0.0.1"
          DB_USERNAME: kbpp
          DB_PASSWORD: kbpp
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          DB_DATABASE: kbpartpicker
          DB_HOST: "127.0.0.1"
          DB_USERNAME: kbpp
          DB_PASSWORD: kbpp

commands:
  poetry_install:
    description: "Execute dependencies install"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "25:5e:16:b7:cb:89:b4:7b:aa:a7:0d:3f:d8:8e:d7:56"
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          command: |
            python -m venv .venv
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - .venv

jobs:
  build-and-test:
    # executor: python/default
    executor: python
    steps:
      - checkout
      - poetry_install
      - run:
          name: Test poetry
          command: |
            poetry run pytest --version
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker image
          command: |
            docker build -t heroku-dockerize:circleci .
            docker images
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web --arg -a $HEROKU_APP_NAME
            heroku container:release web -a $HEROKU_APP_NAME

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
