"""empty message

Revision ID: 1b0b8f02c0a2
Revises: bb5fbdca221e
Create Date: 2021-01-07 13:51:53.283073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b0b8f02c0a2'
down_revision = 'bb5fbdca221e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', postgresql.ENUM('switch', 'case', 'pcb', 'plate', 'keyset', 'kit', 'stabilizer', 'lube', 'film', 'spring', 'tool', 'deskmat', name='product_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
