"""empty message

Revision ID: 56e465a233f1
Revises: 5169a4950f2c
Create Date: 2021-01-06 18:37:18.032165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56e465a233f1'
down_revision = '5169a4950f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size')
    op.drop_column('products', 'layout')
    op.drop_column('products', 'type')
    op.drop_column('products', 'stabilizer_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stabilizer_type', postgresql.ENUM('pcb_screw_in', 'pcb_snap_in', 'plate_mount', name='stabilizer_type'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('layout', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
