"""empty message

Revision ID: 74f558eed8d8
Revises: 1b0b8f02c0a2
Create Date: 2021-01-07 20:04:52.316774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74f558eed8d8'
down_revision = '1b0b8f02c0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', postgresql.ENUM('switch', 'case', 'pcb', 'plate', 'keyset', 'kit', 'stabilizer', 'lube', 'film', 'spring', 'tool', 'deskmat', name='product_type'), nullable=True))
    op.drop_column('products', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type', postgresql.ENUM('switch', 'case', 'pcb', 'plate', 'keyset', name='product_type'), autoincrement=False, nullable=True))
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
