"""empty message

Revision ID: 9867cfc8fa97
Revises: 74f558eed8d8
Create Date: 2021-01-11 23:17:40.434979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9867cfc8fa97'
down_revision = '74f558eed8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'layout')
    op.drop_column('products', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', postgresql.ENUM('six_point_25_u', 'seven_u', 'two_u', name='size_type'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('layout', postgresql.ENUM('forty_percent', 'sixty_percent', 'sixtyfive_percent', 'seventyfive_percent', 'tenkeyless', 'winkeyless', 'hhkb', 'full_size', name='layout_type'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
