"""empty message

Revision ID: a6df4c9ca7af
Revises: 998e3d1a0918
Create Date: 2021-01-11 23:20:47.248980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6df4c9ca7af'
down_revision = '998e3d1a0918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size_type')
    op.drop_column('products', 'layout_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('layout_type', postgresql.ENUM('forty_percent', 'sixty_percent', 'sixtyfive_percent', 'seventyfive_percent', 'tenkeyless', 'winkeyless', 'hhkb', 'full_size', name='layout_type'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('size_type', postgresql.ENUM('six_point_25_u', 'seven_u', 'two_u', name='size_type'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
