"""empty message

Revision ID: b1acc5c489a4
Revises: 3ee175cd092b
Create Date: 2021-01-12 20:45:13.982991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1acc5c489a4'
down_revision = '3ee175cd092b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('layout_type', postgresql.ENUM('forty_percent', 'sixty_percent', 'sixtyfive_percent', 'seventyfive_percent', 'tenkeyless', 'winkeyless', 'frowless', 'full_size', name='layout_type'), nullable=True))
    op.add_column('products', sa.Column('size_type', postgresql.ENUM('six_point_25_u', 'seven_u', 'two_u', 'sixty_kit', 'full_kit', name='size_type'), nullable=True))
    op.drop_column('products', 'layout')
    op.drop_column('products', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('layout', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'size_type')
    op.drop_column('products', 'layout_type')
    # ### end Alembic commands ###
