"""empty message

Revision ID: c5c96080feb2
Revises: 56e465a233f1
Create Date: 2021-01-06 18:37:46.111817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5c96080feb2'
down_revision = '56e465a233f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('layout', postgresql.ENUM('forty_percent', 'sixty_percent', 'sixtyfive_percent', 'seventyfive_percent', 'tenkeyless', 'winkeyless', 'hhkb', 'full_size', name='layout_type'), nullable=True))
    op.add_column('products', sa.Column('size', postgresql.ENUM('six_point_25_u', 'seven_u', 'two_u', name='size_type'), nullable=True))
    op.add_column('products', sa.Column('stabilizer_type', postgresql.ENUM('pcb_screw_in', 'pcb_snap_in', 'plate_mount', name='stabilizer_type'), nullable=True))
    op.add_column('products', sa.Column('type', postgresql.ENUM('switch', 'case', 'pcb', 'plate', 'keyset', name='product_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type')
    op.drop_column('products', 'stabilizer_type')
    op.drop_column('products', 'size')
    op.drop_column('products', 'layout')
    # ### end Alembic commands ###
