"""empty message

Revision ID: d09d024a5f9e
Revises: 1f412acf7316
Create Date: 2021-01-06 19:15:02.920663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09d024a5f9e'
down_revision = '1f412acf7316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('countries', 'currency_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('countries', 'iso_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'iso_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('countries', 'currency_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('countries', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
